### ISSUE TITLE
Realizar el informe "Acuerdo de cliente de PetClinic Services (PSG2-2223-GX-XY)"

### ISSUE THREAD

**Issue by josmorgue3** [gii-is-psg2/psg2-2223-g7-72#108]
En grupo, crear un documento de Acuerdo de Cliente (en español) titulado “ Acuerdo de cliente de PetClinic Services (PSG2-2223-GX-XY) ”, el cual debe incluir la máxima información relevante con respecto al Cliente Modelo de Acuerdo (CA) descrito en clase, no restringido al modelo ofrecido por iTop para contratos de Cliente y Proveedor. Este documento debe estar disponible como un nuevo elemento de menú en la aplicación PetClinic , por lo tanto, en formato HTML, y todos los miembros del grupo deben participar en su elaboración, en la solicitud de extracción correspondiente o en ambos. Las principales características que se deben incluir son:

Duración : Al menos durante todo el curso académico.
Servicios asociados y descripción : Petclinic4CO . Permite a sus usuarios ( propietarios de clínicas ) solicitar la resolución de incidentes, solicitudes de usuarios y estimaciones de Solicitud de cambios (RFC).
Tarifas : Deben existir al menos tres planes ( Básico , Avanzado y Pro ), cuyas condiciones cada grupo puede establecer a su conveniencia, siempre que se cumplan las siguientes restricciones:
El plan Básico no ofrece SLA
El plan Avanzado es el primero que permite a los propietarios de clínicas administrar múltiples clínicas para mascotas.
El plan Pro es el único que ofrece soporte para solicitudes de usuarios y RFC.
La cantidad máxima de veterinarios, visitas mensuales y tipos de mascotas permitidos debe diferir para cada plan.
La disponibilidad del servicio debe ser diferente para cada plan. Esta información debe representarse mediante una matriz, como es habitual en la actualidad.
Acuerdo de nivel de servicio (SLA) : dado que el SLA puede variar para cada servicio, subcategorías de servicio y plan elegido, el documento debe considerar los siguientes requisitos:
Además de las métricas TTO y TTR , al menos una métrica adicional que sea sólida y no esté disponible en iTop.
Descripción del mecanismo de seguimiento.
Períodos de soporte al usuario. Por ejemplo, de lunes a sábado de 9:00 a 22:00, 12x5, 24x7, etc.
Al menos un SLA con tres niveles diferentes de prioridad (urgencia e impacto).
Compensaciones (servicios de crédito) en caso de incumplimiento.
Identificación . Cada contrato de cliente debe tener un número de versión.

Enlace al documento: https://docs.google.com/document/d/1mzDQNkUVD6n4mFZL1BoQ0LQk3g-VTCLW/edit#heading=h.oy2hwzzebgcd

**Comment by RukisRo** [comment]
La documentación se ha revisado por todos los miembros del equipo y se ha añadido a la página web en formato HTML. Se ha mergeado la documentación a la rama develop.
