### ISSUE TITLE
Realizar informe Sprint Planning

### ISSUE THREAD

**Issue by josmorgue3** [gii-is-psg2/psg2-2223-g7-72#118]

**Comment by josmorgue3** [comment]
Necesita revisión de 2 de los miembros del equipo (lectura): 
https://docs.google.com/document/d/1VP9O8VNAUrLsnKT9PldSGy4FzBl1ff9C/edit#heading=h.sjatcg9zvfi8
Añadir comentarios si es necesario.

- [ ] Pedro González Marcos
- [ ]  Rocío López Moyano
- [ ] Victoria de Carmen Ruíz Delgado
- [ ] Manuel Vázquez Martín
- [ ] David Zarandieta Ortiz

**Comment by RukisRo** [comment]
Revisado, todo perfecto.
