### ISSUE TITLE
A2.8a - Crear una nueva funcionalidad en Pet Hotel

### ISSUE THREAD

**Issue by RukisRo** [gii-is-psg2/psg2-2223-g7-72#18]
Cree una función de Pet Hotel, que permita a los clientes enviar detalles sobre para qué mascota desean reservar una habitación, así como las fechas de inicio y finalización de la reserva.
Cada cambio debe desarrollarse siguiendo la estrategia de bifurcación definida en el grupo, y la rama debe enviarse al repositorio remoto del grupo antes de fusionarse, asegurándose de que no se elimine una vez finalizada la función.

**Comment by pgmarc** [comment]
Cambiar 
```java 
public Owner findByUsername(@Param("username") String username);`
```

A esto

```java 
public Owner findOwnerByUsername(String username);
```
Spring ya te hace las queries si usas su nomeclatura

Comprobar que funciona

**Comment by pgmarc** [comment]
Cambiar el nombre de la clase petController2 a una que tenga más significado. Las clases tiene que estar en UpperCamelCase

**Comment by pgmarc** [comment]
Renombrar atributo service del PetController a petHotelService

**Comment by pgmarc** [comment]
Cambiar url menu.tag  de myPets a petHotels/myProfile

**Comment by pgmarc** [comment]
Se pueden borrar las reservas de otro owner siendo otro owner

**Comment by RukisRo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/18?planning-poker) with Zenhub @davidzarandieta @josmorgue3 @manvazmar3 @pgmarc @VictoriaCRD
