### ISSUE TITLE
A2.E.2 Convertir el informe de la metodología a MD

### ISSUE THREAD

**Issue by pgmarc** [gii-is-psg2/psg2-2223-g7-72#30]
***A2.E.2.*** 
(E2 - 0,2 puntos) - Como grupo, use Markdown y posiblemente herramientas relacionadas para generar los informes técnicos de A2.6 y A2.7 y almacenarlos en el repositorio. El envío final aún debe incluir los informes en formato PDF con el formato correcto (incluidos los encabezados, la tabla de contenido, etc.). Algunas herramientas que pueden ser útiles son https://github.com/geraked/mdpdfbook o https://github.com/rust-lang/mdBook .

Pasos a seguir para realizar la tarea:

- Para instalar `mdbook` necesitas `rust` instalado.
- Dentro de la carpeta docs hacer `mdbook init` para iniciar un `book` de markdown.
- Estructurar el `SUMMARY.md`. ⚠ Todos los documentos que se hagan deben estar en este `SUMMARY.md`. Bajo ningún concepto cambiar de nombre a este archivo.
- Crear carpetas para organizar los archivos markdown.
- Por último descargar el [exe](https://github.com/geraked/mdpdfbook/releases/tag/v1.0.1) para convertir todo lo que tenemos a pdf.

## Criterios aceptación

- Por lo que deben estar en dos carpetas distintas
- En este issue se realizará la tarea de documentar en md el informe de la metodología.
- Generar pdf con el resultado final.

**Comment by RukisRo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/30?planning-poker) with Zenhub @davidzarandieta @josmorgue3 @manvazmar3 @pgmarc @VictoriaCRD
