### ISSUE TITLE
A2.E.1 Ampliar el informe técnico de historial de cambios realizados para A2.8 y A2.9

### ISSUE THREAD

**Issue by VictoriaCRD** [gii-is-psg2/psg2-2223-g7-72#31]
A2.E.1. (E2 - 0,2 puntos) - 

- [x] Como grupo, amplía el informe técnico creado como resultado de A2.6 para incluir también el historial de cambios realizados para A2.8 y A2.9. 

- [x] El documento también debe incluir una discusión sobre los beneficios y desventajas de usar la estrategia de ramificación.
- [x] Revisar por todos los miembros del equipo

**Comment by josmorgue3** [comment]
Corregidas algunas faltas. DONE

**Comment by RukisRo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/31?planning-poker) with Zenhub @davidzarandieta @josmorgue3 @manvazmar3 @pgmarc @VictoriaCRD
