### ISSUE TITLE
Realizar un informe de la Retrospective

### ISSUE THREAD

**Issue by VictoriaCRD** [gii-is-psg2/psg2-2223-g7-72#33]
Retrospectiva de Sprint realizada, análisis de cada Sprint y plan de acción para mejorar el trabajo en equipo para el Sprint 3.

**Comment by josmorgue3** [comment]
Necesita revisión

**Comment by RukisRo** [comment]
Revisado, me parece perfecto

**Comment by VictoriaCRD** [comment]
Sprint Retrospective completa con todos los datos necesarios
