### ISSUE TITLE
Realizar un informe del Sprint Review

### ISSUE THREAD

**Issue by VictoriaCRD** [gii-is-psg2/psg2-2223-g7-72#34]
Demostraciones de revisión de Sprint y acciones tomadas.

**Comment by josmorgue3** [comment]
Falta rellenar la tabla de control de versiones y te diría de concretar más a que se refiere con lo de los espacios

**Comment by josmorgue3** [comment]
Otra cosa mira el índice porque creo que el corchete hay que borrarlo

**Comment by VictoriaCRD** [comment]
Cambios realizados. Se ha actualizado el índice y la tabla de control de versiones

**Comment by josmorgue3** [comment]
Te he corregido una falta pero ya esta todo bien. DONE

**Comment by RukisRo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/34?planning-poker) with Zenhub @davidzarandieta @josmorgue3 @manvazmar3 @pgmarc @VictoriaCRD
