### ISSUE TITLE
Revisión final al proyecto

### ISSUE THREAD

**Issue by VictoriaCRD** [gii-is-psg2/psg2-2223-g7-72#48]
Revisión final general para comprobar que todo el proyecto está completo con las funcionalidades requeridas a lo largo de este sprint, funciona correctamente y contiene toda la documentación necesaria para poder realizar la release del proyecto.

**Comment by RukisRo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/48?planning-poker) with Zenhub @davidzarandieta @josmorgue3 @manvazmar3 @pgmarc @VictoriaCRD
