### ISSUE TITLE
Preparación entrega y corroboración con la rúbrica de evaluación

### ISSUE THREAD

**Issue by VictoriaCRD** [gii-is-psg2/psg2-2223-g7-72#49]
Comprobar que se cumple, en la medida de lo posible, la rúbrica de evaluación del proyecto para autoevaluar el trabajo realizado durante este Sprint.

**Comment by RukisRo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/49?planning-poker) with Zenhub @davidzarandieta @josmorgue3 @manvazmar3 @pgmarc @VictoriaCRD
