### ISSUE TITLE
crear rama epic/causas

### ISSUE THREAD

**Issue by RukisRo** [gii-is-psg2/psg2-2223-g7-72#52]
crear una rama feature/causas a partir de develop para la implementación de funcionalidad causas. 

La rama se fusionará con develop una vez se haya hecho test de la funcionalidad.

**Comment by josmorgue3** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/52?planning-poker) with Zenhub @RukisRo

**Comment by RukisRo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/52?planning-poker) with Zenhub @pgmarc

**Comment by RukisRo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/52?planning-poker) with Zenhub @josmorgue3

**Comment by RukisRo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/52?planning-poker) with Zenhub @manvazmar3

**Comment by RukisRo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/52?planning-poker) with Zenhub @davidzarandieta

**Comment by pgmarc** [comment]
Ya está creada la rama
