### ISSUE TITLE
Implementar nueva funcionalidad VALIDACIÓN

### ISSUE THREAD

**Issue by RukisRo** [gii-is-psg2/psg2-2223-g7-72#56]
Implemente una funcionalidad de validación en la creación de reservas de su hotel para mascotas que asegure que no hay reservas simultáneas en el hotel para la misma mascota.

**Comment by pgmarc** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/56?planning-poker) with Zenhub @manvazmar3
