### ISSUE TITLE
Implementar nueva funcionalidad ADOPCIONES

### ISSUE THREAD

**Issue by RukisRo** [gii-is-psg2/psg2-2223-g7-72#57]
Cree una funcionalidad de adopciones . Como propietario, podemos crear una solicitud de adopción cuando no podamos cuidar de nuestra mascota. Otros propietarios podrían enumerar las mascotas disponibles para adopción y presentar una solicitud ( las solicitudes de adopción tendrán una descripción de cómo el solicitante cuidará de la mascota). Si el dueño original aprueba la solicitud, la mascota será transferida al solicitante y él/ella será el nuevo dueño de la mascota.

**Comment by pgmarc** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/57?planning-poker) with Zenhub @davidzarandieta

**Comment by pgmarc** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/57?planning-poker) with Zenhub @manvazmar3

**Comment by davidzarandieta** [comment]
Tarea realizada por manvazmar3 y davidzarandieta. Responsabilidad de manvazmar3
