### ISSUE TITLE
crear rama release/1.2.0 y desplegar

### ISSUE THREAD

**Issue by RukisRo** [gii-is-psg2/psg2-2223-g7-72#58]
En grupo, una vez realizados los cambios anteriores, preparar una versión del proyecto Petclinic, creando una rama de versión correspondiente. En esta rama de lanzamiento, todos los miembros del grupo deben eliminar cualquier error y advertencia que esté presente en todos los archivos fuente del código desarrollado, hasta el momento en que se inicie el lanzamiento. Como resultado final de ese lanzamiento, la nueva versión de la aplicación Petclinic debe implementarse en App Engine , accesible bajo la misma URL utilizada en el sprint S2.

Además, como grupo, una vez que se realiza el lanzamiento de S3 a nivel de código fuente, cree un lanzamiento en el repositorio de GitHub, cargando el archivo .war que se genera en la carpeta de destino de la rama maestra como el archivo binario. Usa la etiqueta del release generado en el sprint S3. El lanzamiento debe incluir como su descripción los cambios realizados en base a los mensajes de las solicitudes de extracción fusionadas. Por favor, utilice la opción "generar notas de lanzamiento" proporcionada por GitHub para automatizar la inclusión de dicho contenido.

**Comment by RukisRo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/58?planning-poker) with Zenhub @VictoriaCRD

**Comment by pgmarc** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/58?planning-poker) with Zenhub @davidzarandieta

**Comment by pgmarc** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/58?planning-poker) with Zenhub @manvazmar3

**Comment by RukisRo** [comment]
Revisado el .jar

**Comment by manvazmar3** [comment]
He visto el .jar
