### ISSUE TITLE
Realizar informe "Métricas de Proceso Ágil y Recursos" del Sprint 2

### ISSUE THREAD

**Issue by RukisRo** [gii-is-psg2/psg2-2223-g7-72#59]
Elaborar en grupo un informe técnico (en español) titulado “ Métricas de Proceso Ágil y Recursos ”. Este documento debe contener al menos los siguientes elementos:

For Sprint S2:
BurnDown chart,
total history points delivered,
percentage of history points delivered.

Documento: https://docs.google.com/document/d/13CXnSWeF_9d_oCfuGO8_EeITdcda8cL-/edit

**Comment by RukisRo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/59?planning-poker) with Zenhub @VictoriaCRD

**Comment by RukisRo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/59?planning-poker) with Zenhub @manvazmar3

**Comment by VictoriaCRD** [comment]
Necesita revisión de todos los miembros del equipo (lectura): 
Añadir comentarios si es necesario.

- [ ] Pedro González Marcos
- [ ] Rocío López Moyano
- [ ] José Manuel Moreno Guerrero
- [ ] Manuel Vázquez Martín
- [ ] David Zarandieta Ortiz

**Comment by RukisRo** [comment]
Revisado, he puesto algunos comentarios.

**Comment by josmorgue3** [comment]
He dejado un comentario en la gráfica

**Comment by pgmarc** [comment]
He realizado un comentario en el documento

**Comment by davidzarandieta** [comment]
Revisado

**Comment by manvazmar3** [comment]
Revisado
