### ISSUE TITLE
Realizar informe “Análisis del Código Fuente y Métricas Asociadas”  Sprint 3

### ISSUE THREAD

**Issue by RukisRo** [gii-is-psg2/psg2-2223-g7-72#61]
En grupo, elaboren un informe técnico (en español) titulado “ Análisis del Código Fuente y Métricas Asociadas ” sobre los resultados de analizar su proyecto con SonarCloud (según los comunicados generados en S2 y S3, analizando el código en las ramas maestras para las confirmaciones correspondientes). Dicho informe debe describir los valores de las métricas del código fuente calculadas, los tipos de problemas encontrados en el análisis y sus causas. Este documento debe contener al menos los siguientes elementos:

Una captura de pantalla del panel de Sonar Cloud para el análisis de su proyecto y una descripción de las métricas proporcionadas en el panel y sus valores.
Descripción y análisis de los posibles errores encontrados en el repositorio (en el apartado de fiabilidad, sobre medidas).
Descripción y análisis de los diferentes tipos de olores de código encontrados en los análisis (en el apartado de mantenibilidad, sobre medidas). Para cada tipo de código olor, el informe debe describir. 
El nombre y la descripción del olor del código.
Las diferentes causas del olor en su base de código
Una evaluación justificada de la gravedad del olor del código.
Una breve descripción de cómo solucionarlo en función de las causas.
Conclusiones sobre los resultados de los análisis.

Documento: https://docs.google.com/document/d/1lknKwjXn9L8AEDGhOWoba8XxdO5SDUGD/edit

**Comment by RukisRo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/61?planning-poker) with Zenhub @VictoriaCRD

**Comment by pgmarc** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/61?planning-poker) with Zenhub @davidzarandieta

**Comment by pgmarc** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/61?planning-poker) with Zenhub @manvazmar3

**Comment by RukisRo** [comment]
- [ ] Pedro González Marcos
- [ ] José Manuel Moreno Guerrero
- [ ] Victoria de Carmen Ruíz Delgado
- [ ] Manuel Vázquez Martín
- [ ] David Zarandieta Ortiz
