### ISSUE TITLE
Realizar informe del "Sprint Planning"

### ISSUE THREAD

**Issue by RukisRo** [gii-is-psg2/psg2-2223-g7-72#62]
Documento: https://docs.google.com/document/d/1Ti3zR3DrZhEM3E9Tptbi8CISDSkYqDgY/edit

**Comment by RukisRo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/62?planning-poker) with Zenhub @VictoriaCRD

**Comment by pgmarc** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/62?planning-poker) with Zenhub @manvazmar3

**Comment by pgmarc** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/62?planning-poker) with Zenhub @davidzarandieta

**Comment by RukisRo** [comment]
Necesita revisión de todos los miembros del equipo (lectura): 
Añadir comentarios si es necesario.

- [ ] Pedro González Marcos
- [ ] José Manuel Moreno Guerrero
- [ ] Victoria de Carmen Ruíz Delgado
- [ ] Manuel Vázquez Martín
- [ ] David Zarandieta Ortiz

**Comment by pgmarc** [comment]
Ya he revisado el documento, he comentado algunos añadidos para el documento

**Comment by josmorgue3** [comment]
Si el sprint planning fue lo que hicimos en la clase no coincide con lo indicado en el clockify
