### ISSUE TITLE
Realizar informe de daily 4

### ISSUE THREAD

**Issue by RukisRo** [gii-is-psg2/psg2-2223-g7-72#63]
Documento: https://docs.google.com/document/d/18RMQNVMNpoQMoZ5n9JuPlZ08-xPCYHjH/edit

**Comment by RukisRo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/63?planning-poker) with Zenhub @VictoriaCRD

**Comment by pgmarc** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/63?planning-poker) with Zenhub @manvazmar3

**Comment by pgmarc** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/63?planning-poker) with Zenhub @davidzarandieta

**Comment by RukisRo** [comment]
Revisado, se cierra

**Comment by VictoriaCRD** [comment]
Revisado el documento
