### ISSUE TITLE
Realizar informe de "Review"

### ISSUE THREAD

**Issue by RukisRo** [gii-is-psg2/psg2-2223-g7-72#65]
Documento: https://docs.google.com/document/d/14C2VmQ27mugB9FL4kRczHJpb30MTl81U/edit

**Comment by pgmarc** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/65?planning-poker) with Zenhub @manvazmar3

**Comment by pgmarc** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/65?planning-poker) with Zenhub @davidzarandieta

**Comment by pgmarc** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/65?planning-poker) with Zenhub @VictoriaCRD

**Comment by RukisRo** [comment]
Revisado
