### ISSUE TITLE
Repasar Rúbrica

### ISSUE THREAD

**Issue by RukisRo** [gii-is-psg2/psg2-2223-g7-72#66]
Comprobar mediante la rúbrica del entregable, que hemos realizado todos los puntos necesarios

**Comment by RukisRo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/66?planning-poker) with Zenhub @VictoriaCRD

**Comment by pgmarc** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/66?planning-poker) with Zenhub @manvazmar3

**Comment by pgmarc** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/66?planning-poker) with Zenhub @davidzarandieta

**Comment by pgmarc** [comment]
Se ha realizado la rúbrica. He comentado en el drive aspectos a tener en cuenta de cara al entregable.

**Comment by VictoriaCRD** [comment]
Visualizados los comentarios que has hecho, se corregirán cuanto antes

**Comment by RukisRo** [comment]
Revisado
