### ISSUE TITLE
Traducción de la vista Causas

### ISSUE THREAD

**Issue by RukisRo** [gii-is-psg2/psg2-2223-g7-72#74]

**Comment by RukisRo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2223-g7-72-64044efb904ea258e6cac26e/issues/gii-is-psg2/psg2-2223-g7-72/74?planning-poker) with Zenhub @davidzarandieta @josmorgue3 @manvazmar3 @pgmarc @VictoriaCRD

**Comment by VictoriaCRD** [comment]
Muy buena traducción

**Comment by RukisRo** [comment]
Revisado, lo paso a DONE
