### ISSUE TITLE
Correcciones Pet-Hotel Sprint2

### ISSUE THREAD

**Issue by RukisRo** [gii-is-psg2/psg2-2223-g7-72#87]

**Comment by manvazmar3** [comment]
Tarea realizada por davidzarandieta y manvazmar3. Responsabilidad de davidzarandieta

**Comment by manvazmar3** [comment]
En la rama epic/adoption, ya no puedes hacer una reserva si no es el propio owner

**Comment by RukisRo** [comment]
Revisado
